version: 2
updates:
  # DÃ©pendances Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "fil04331"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"

  # Actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "fil04331"
    labels:
      - "ci/cd"
